name: Integration Tests2

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  playwright:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Get npm store directory
        uses: actions/cache@v3
        id: npm-cache
        with:
          path: |
            **/node_modules
            ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
            ${{ runner.os }}
      - if: ${{ steps.npm-cache.outputs.cache-hit != 'true' }}
        run: npm ci

      - name: Build the application
        run: npm run build

      - name: Start the application
        run: npm start &
        shell: bash

      - name: Install dependencies and Playwright
        run: |
          cd src/e2e/playwright
          npm ci
          npx playwright install --with-deps

      - name: Run Playwright tests
        run: npm run test:e2e
        working-directory: src/e2e/playwright

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: src/e2e/playwright/playwright-report/
          retention-days: 30
